[package]
name = "ruby_rqrr"
version = "0.1.0"
edition = "2021"
authors = ["Shawn Jordan <shawn.jordan@me.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
