name: CI/CD

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} Linting and Testing on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby:
          - "3.3.7"
          - "3.4.1"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rust-version: "1.85.1"
          bundler-cache: true
          cargo-cache: true
          rubygems: "3.6.2"
      - name: Install the Ruby dependencies
        run: bin/setup
      - name: StandardRb check
        run: bundle exec standardrb
      - name: Compile the Gem
        run: bundle exec rake compile
      - name: Run Tests
        run: bundle exec rake test

  promote_compiled:
    needs: test
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/v')
    name: Promote ${{ matrix.os }} Pre-Compiled Gem
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4.1"
          rust-version: "1.85.1"
          bundler-cache: true
          cargo-cache: true
          rubygems: "3.6.2"
      - name: Install the Ruby dependencies
        run: bin/setup
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          bundle exec rake native
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN  }}
  promote_standard:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Promote Uncompiled Gem
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4.1"
          rust-version: "1.85.1"
          bundler-cache: true
          cargo-cache: true
          rubygems: "3.6.2"
      - name: Install the Ruby dependencies
        run: bin/setup
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          bundle exec rake build
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN  }}
